# Generated by Django 5.1.1 on 2024-10-08 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='coursesdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='schoolapp/images')),
            ],
        ),
        migrations.CreateModel(
            name='payment_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pay', models.CharField(default='', max_length=30)),
                ('cardnos_pay', models.IntegerField(default=0)),
                ('cardname_pay', models.CharField(default='', max_length=100)),
                ('seccode_pay', models.CharField(default='', max_length=30)),
                ('exdate_pay', models.DateField()),
                ('selected_option', models.CharField(blank=True, choices=[('wiretransfer', 'wire tranfer'), ('paypal', 'Paypal'), ('payoner', 'Payoner'), ('creditcard', 'Credit card')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cart_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cartitems_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='schoolapp.cart_db')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.coursesdb')),
            ],
        ),
    ]
