# Generated by Django 5.1.1 on 2024-10-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carts_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imges', models.ImageField(default='', upload_to='schoolapp/images')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=50)),
                ('userss', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitems_db',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems_db',
            name='item',
        ),
        migrations.DeleteModel(
            name='cart_db',
        ),
        migrations.DeleteModel(
            name='cartitems_db',
        ),
    ]
