# Generated by Django 5.1.1 on 2024-10-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_carts_db_remove_cartitems_db_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts_db',
            name='proname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.coursesdb'),
        ),
        migrations.AlterField(
            model_name='carts_db',
            name='userss',
            field=models.IntegerField(),
        ),
    ]
