# Generated by Django 5.1.1 on 2024-10-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_carts_db_proname_alter_carts_db_userss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts_db',
            name='userss',
            field=models.CharField(max_length=50),
        ),
    ]
