# Generated by Django 5.1.1 on 2024-10-31 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_comment_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='schoolapp/images')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.coursesdb')),
            ],
        ),
    ]
