# Generated by Django 5.1.1 on 2024-11-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_subjectdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
